CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE USERS (
    ID UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
)