CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE POSTS (
    ID UUID PRIMARY KEY NOT NULL DEFAULT uuid_generate_v4(),
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    USER_ID UUID NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)